[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-ssh-config"
description = "OpenSSH config grammar for tree-sitter"
version = "0.3.0"
keywords = ["incremental", "parsing", "tree-sitter", "ssh"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed"
]
requires-python = ">=3.8"
license.text = "MIT"
readme = "README.md"

[[project.authors]]
name = "ObserverOfTime"
email = "chronobserver@disroot.org"

[project.urls]
Homepage = "https://github.com/tree-sitter-grammars/tree-sitter-ssh-config"

[project.optional-dependencies]
core = ["tree-sitter~=0.21"]

[tool.cibuildwheel]
build = "cp38-*"
build-frontend = "build"
