name: Test grammar

on:
  push:
    branches: ["*"]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    branches: ["*"]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    uses: tree-sitter-grammars/.github/.github/workflows/ci.yml@main
